[package]
name = "rust-gpx-analyzer"
version = "0.0.1"
authors = ["paulcarroty@users.noreply.github.com"]
edition = "2021"


[dependencies]
geoutils = "0.5.1"
gpx = "0.8.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

